export const PrivacySideArray = [
    {
        title:"Eligibility",
        listItems:[
            `At Orbit Finance, we require that all users of our website and services must be at least 18 years old and legally capable of entering into binding agreements. By accessing or using our website or services, you represent and warrant that you meet these eligibility requirements. In addition, our services are not intended for use by individuals under the age of 18 or individuals who are prohibited from accessing or using our website or services under applicable laws. If we become aware that an individual under the age of 18 has provided us with personal information, we will take steps to promptly delete such information.`,
            `Please note that Orbit Finance may also impose additional eligibility requirements for certain products or services that we offer. These requirements will be communicated to you at the time of your application or registration. If you have any questions or concerns about our eligibility requirements, please contact us using the information provided in the Contact Us section of this policy.`
        ]
    },
    {
        title:"Consent",
        listItems:[
            `By using our website or services, you acknowledge and consent to the collection, use, and disclosure of your personal information in accordance with this privacy policy. If you provide us with personal information about another individual, you must obtain their consent before providing the information to us. You may withdraw your consent to the collection, use, or disclosure of your personal information at any time, subject to legal or contractual restrictions. However, withdrawing your consent may prevent us from providing you with certain services or information. To withdraw your consent, or to request access to or correction of your personal information, please contact us using the information provided in the Contact Us section of this policy. By providing your personal information to us, you acknowledge that you have read and understood this privacy policy, and agree to its terms and conditions. At Orbit Finance, we understand the importance of privacy and the protection of personal information. This privacy policy outlines our practices regarding the collection, use, and disclosure of personal information that we collect through our website and services. We are committed to complying with all applicable data protection laws and regulations, including the Nigerian Data Protection Regulation 2019 (NDPR), and will ensure that any personal information we collect is treated with the utmost care and respect.`
        ]
    },
    {
        title:"Information Collection",
        listItems:[
            `We take the collection of personal information very seriously, as we understand that the information we collect is sensitive and requires utmost protection. We only collect personal information that is necessary for the provision of our financial services and for complying with legal obligations. We may collect personal information through various means, such as through our website, email, phone calls, or other methods of communication. The personal information we collect may include but is not limited to your name, email address, phone number, date of birth, address, bank details, and other information that is relevant to our services. In addition, we may also collect personal information through third-party sources, such as credit bureaus, government agencies, or other service providers.`,
            `This information is collected in order to verify your identity and to conduct credit checks to determine eligibility for our financial services. At all times, we ensure that the personal information collected is done in accordance with the Nigerian Data Protection Regulation 2019 (NDPR), as well as other applicable laws and regulations. We take all necessary steps to ensure that any personal information we collect is accurate, complete, and up-to-date and that it is only collected for the purposes outlined in this privacy policy.`
        ]
    },
    {
        title:"Use of Information",
        listItems:[
            `We use personal information for various purposes that are necessary for the provision of our financial services and for complying with legal obligations. One of the primary purposes for which we use personal information is to provide financial services to our customers. This includes activities such as opening and maintaining accounts, processing transactions, and providing customer support. In addition, we also use personal information to verify the identity of our customers, which is an important part of ensuring the security and integrity of our financial services. Furthermore, we use personal information to comply with legal obligations, such as anti-money laundering (AML) and know-your-customer (KYC) regulations. These regulations require us to collect and maintain certain information about our customers, and to report any suspicious transactions to regulatory authorities. Another important use of personal information is to conduct fraud prevention and detection activities. We may use personal information to monitor transactions and identify any potentially fraudulent activity, which is important for protecting our customers and the integrity of our financial services. We also use personal information to improve our services and customer experience. This includes activities such as conducting market research and analysis to better understand the needs and preferences of our customers and using this information to develop new products and services that better meet their needs. Finally, we use personal information to communicate with our customers about our products and services, as well as to provide important updates and notifications. This includes activities such as sending marketing materials and newsletters, as well as providing important information about changes to our services or policies.`
        ]
    },
    {
        title:"security",
        listItems:[
            `At Orbit Finance, we use 256-bit encryption to protect personal information both in transit and at rest. This strong form of encryption is widely used in the financial industry and involves using a 256-bit key to encrypt and decrypt data, making it virtually impossible for unauthorized individuals to access or decipher encrypted data. To further ensure the security of personal information, we have implemented a range of physical, technical, and administrative safeguards. These include restricted access to our premises, systems, and data centres, firewalls, encryption, and regular backups of data. Our servers are located in secure data centres that are protected by physical and electronic security measures to prevent unauthorized access to our systems and data. We also require our employees and third-party service providers to comply with strict confidentiality and security obligations, including regular training on privacy and security best practices and ongoing monitoring of compliance.In addition, we conduct regular audits and assessments of our privacy and security practices to identify potential vulnerabilities and areas for improvement. We have developed a data breach response plan that outlines the steps we will take in the event of a breach of personal information, including notifying affected individuals, regulators, and law enforcement agencies, and implementing additional safeguards to prevent similar incidents from occurring in the future. We also comply with applicable data protection laws and regulations, including the General Data Protection Regulation (GDPR) and the Nigerian Data Protection Regulation (NDPR). This includes implementing appropriate technical and organizational measures to ensure the security of personal information, as well as providing individuals with the right to access, correct, and delete their personal information.`
        ]
    },
    {
        title:"Fraud Prevention",
        listItems:[
            `At Orbit Finance, we take fraud prevention very seriously. We have implemented various security measures and fraud detection techniques to ensure the safety and security of our customers' personal and financial information. We may collect personal information, such as name, address, and date of birth, as well as financial information, such as bank account and card details, to detect and prevent fraud. This information may be used in conjunction with third-party fraud detection services to help identify and prevent fraudulent transactions. We may also monitor your account for any suspicious activity, such as multiple failed login attempts or unusual transaction patterns, and may contact you to verify any suspicious activity. If we suspect that your account has been compromised, we may take additional measures, such as disabling your account or contacting law enforcement.`,
            `Please note that we will never ask for your personal or financial information via email or phone, and we will never send you unsolicited emails or texts requesting your login credentials or other sensitive information. If you receive any suspicious emails or messages, please do not respond or provide any personal information. If you believe that your account has been compromised or that you have been the victim of fraud, please contact us immediately using the information provided in the Contact Us section of this policy. By using our website or services, you acknowledge and agree that Orbit Finance may collect and use your personal and financial information for fraud prevention purposes. We take the security of your information very seriously and will make every effort to ensure that your information is protected against unauthorized access, use, or disclosure.`
        ]
    },
    {
        title:"Data Analytics and Benchmarking",
        listItems:[
            `Orbit Finance may use data analytics and benchmarking to improve our products, services, and customer experience. We may collect and analyse data from various sources, including our website, mobile applications, and other sources, to gain insights into customer behaviour, preferences, and usage patterns. We may use third-party analytics providers to assist us in these efforts. These providers may use cookies, web beacons, and other tracking technologies to collect information about your use of our website and services. This information may be used to generate reports and analyses that help us understand how customers interact with our products and services, identify areas for improvement, and make informed business decisions. We may also use data analytics and benchmarking to develop new products and services and to improve the performance and effectiveness of our existing offerings. We may share de-identified or aggregated data with our business partners, affiliates, and service providers for these purposes. Please note that we will not use data analytics or benchmarking to make decisions that significantly affect you, such as decisions related to employment, credit, insurance, or other benefits. If we ever use personal information for these purposes, we will obtain your consent or provide you with an opportunity to opt out, as required by applicable law. If you have any questions or concerns about our data analytics and benchmarking practices, please contact us using the information provided in the Contact Us section of this policy.`
        ]
    },
    {
        title:"Confidentiality",
        listItems:[
            `At Orbit Finance, we take the confidentiality and security of personal information very seriously. We have implemented technical and organizational measures to ensure that personal information is protected against unauthorized access, use, disclosure, or alteration. We also require our employees and third-party service providers to adhere to strict confidentiality obligations in relation to personal information. We limit access to personal information to those individuals who have a business need to know such information in order to perform their job responsibilities and we conduct regular security audits and risk assessments to ensure that our security measures remain effective and up to date.  We also conduct regular security audits and risk assessments to ensure that our security measures remain effective and up to date. In the event of a data breach or other security incident involving personal information, we will take appropriate steps to mitigate the impact of the incident and to prevent similar incidents from occurring in the future. We will also comply with any legal or regulatory notification obligations in relation to the incident. We may use third-party service providers to store or process personal information on our behalf. These service providers are required to adhere to strict confidentiality and security obligations in relation to personal information and are only permitted to use personal information for the purposes for which it was disclosed. We will only disclose personal information to third parties where we are legally permitted or required to do so, such as to comply with a court order or legal obligation, or where we believe it is necessary to protect our rights or the rights of others.`
        ]
    },
    {
        title:"Cookies",
        listItems:[
            `At Orbit Finance, we use cookies on our website to enhance the user experience and to collect information about how visitors use our site. Cookies are small text files that are placed on your device when you visit our website. They are widely used to make websites work more efficiently and to provide information to the website owners. We use both session cookies and persistent cookies on our website. Session cookies are temporary cookies that are deleted when you close your browser, while persistent cookies remain on your device until they expire or are deleted.`,
            `The cookies we use on our website include`,
            {
                listStyle:"unorganized",
                listItems:[
                    `Essential cookies These cookies are necessary for the website to function properly and cannot be turned off in our system. They are usually set in response to actions made by you, such as setting your privacy preferences, logging in, or filling in forms.`,
                    `Analytical cookies These cookies help us understand how visitors interact with our website by collecting information such as the number of visitors, the pages visited, and the sources of traffic. This information is used to improve the website and enhance the user experience.`,
                    `Functional cookies These cookies enable the website to provide enhanced functionality and personalization, such as remembering your preferences and settings.`,
                    `Marketing cookies These cookies are used to track visitors across websites with the intention of displaying relevant advertisements.`,
                ]
            },
            `By using our website, you consent to our use of cookies in accordance with this policy. You can control the use of cookies through your browser settings. However, please note that disabling cookies may affect the functionality of our website. We may also use third-party cookies on our website for analytical or marketing purposes. These cookies are subject to the privacy policies of the respective third-party providers, and we do not have control over the information collected by these cookies. We encourage you to review the privacy policies of these third-party providers for more information on their use of cookies.`
        ]
    },
    {
        title:"Data Subject Rights",
        listItems:[
            `We recognize the importance of data subject rights and are committed to providing individuals with transparency, choice, and control over their personal information. We comply with all applicable data protection laws and regulations, including the General Data Protection Regulation (GDPR) and the Nigerian Data Protection Regulation (NDPR), and we have implemented measures to ensure that individuals can exercise their rights effectively.Under applicable data protection laws and regulations, individuals have the right to`,
            {
                listStyle:"organised",
                listItems:[
                    `Access their personal information Individuals have the right to access the personal information we hold about them and to request a copy of that information. We will respond to such requests within the timeframes set out in applicable data protection laws and regulations.`,
                    `Correct their personal information Individuals have the right to request that we correct any inaccurate or incomplete personal information we hold about them. We will respond to such requests within the timeframes set out in applicable data protection laws and regulations.`,
                    `Delete their personal information Individuals have the right to request that we delete their personal information in certain circumstances, such as when the information is no longer necessary for the purposes for which it was collected. We will respond to such requests within the timeframes set out in applicable data protection laws and regulations.`,
                    `Object to the processing of their personal information Individuals have the right to object to the processing of their personal information in certain circumstances, such as where the processing is based on our legitimate interests. We will respond to such requests within the timeframes set out in applicable data protection laws and regulations.`,
                    `Restrict the processing of their personal information Individuals have the right to request that we restrict the processing of their personal information in certain circumstances, such as where the accuracy of the information is disputed or where the processing is unlawful. We will respond to such requests within the timeframes set out in applicable data protection laws and regulations.`,
                    `Port their personal information Individuals have the right to receive their personal information in a structured, commonly used, and machine-readable format, and to transmit that information to another data controller. We will respond to such requests within the timeframes set out in applicable data protection laws and regulations.`
                ]
            },
            `To exercise these rights, individuals can contact us using the contact details provided in this privacy policy. We will respond to all requests within the timeframes set out in applicable data protection laws and regulations, and we may need to request additional information to verify the identity of the individual making the request.`
        ]
    },
    {
        title:"Data transfers and sharing",
        listItems:[
            `We may transfer personal information to third parties in accordance with this privacy policy. We take reasonable steps to ensure that any third parties to whom we disclose personal information are bound by appropriate confidentiality and privacy obligations, and that personal information is only used by those third parties for the purposes for which it was disclosed. We may disclose personal information to our affiliates, service providers, and other third-party organizations in order to provide individuals with the services they have requested, to operate our business, or to comply with legal or regulatory requirements. These third-party organizations may be located in other countries and may have different data protection laws than those in the country in which personal information was originally collected. We take appropriate steps to ensure that personal information transferred to third-party organizations is adequately protected in accordance with applicable data protection laws and regulations. Where required by law, we will obtain individuals' consent before transferring personal information to third-party organizations. In addition to transfers to third-party organizations, we may share personal information with government agencies, regulators, courts, and other third parties where we believe it is necessary to comply with applicable laws and regulations, to protect our rights or the rights of others, or to prevent or detect fraud or other illegal activities. If personal information is transferred to a third party located in a country that does not provide an adequate level of data protection, we will take appropriate steps to ensure that personal information is adequately protected, such as by entering into data transfer agreements containing standard contractual clauses approved by the European Commission, or by other means as required by applicable laws and regulations.`
        ]
    },
    {
        title:"Retention of Information",
        listItems:[
            `By using our website or services, you acknowledge and consent to the collection, use, and disclosure of your personal information in accordance with this privacy policy. If you provide us with personal information about another individual, you must obtain their consent before providing the information to us. You may withdraw your consent to the collection, use, or disclosure of your personal information at any time, subject to legal or contractual restrictions. However, withdrawing your consent may prevent us from providing you with certain services or information. To withdraw your consent, or to request access to or correction of your personal information, please contact us using the information provided in the Contact Us section of this policy. By providing your personal information to us, you acknowledge that you have read and understood this privacy policy, and agree to its terms and conditions. At Orbit Finance, we understand the importance of privacy and the protection of personal information. This privacy policy outlines our practices regarding the collection, use, and disclosure of personal information that we collect through our website and services. We are committed to complying with all applicable data protection laws and regulations, including the Nigerian Data Protection Regulation 2019 (NDPR), and will ensure that any personal information we collect is treated with the utmost care and respect.`
        ]
    },
    {
        title:"Job Applicants",
        listItems:[
            `At Orbit Finance, we value the privacy of our job applicants and are committed to protecting their personal information. This section outlines our practices regarding the collection, use, disclosure, and retention of personal information from job applicants.`,
            `Information Collection`,
            `We collect personal information from job applicants during the recruitment process, which may include your name, contact details, resume, cover letter, educational and employment history, and other information you provide us. We may also collect additional information through interviews and assessments.`,
            `Use of Information`,
            `We use the personal information collected from job applicants for the purpose of evaluating your candidacy for employment, communicating with you about the recruitment process, and verifying the information provided. We may also use the information to conduct background checks, reference checks, and other screening processes as necessary.`,
            `Disclosure of Information`,
            `We may disclose your personal information to third-party service providers who assist us in the recruitment process, such as background check providers and applicant tracking systems. We may also share your information with other entities within the Orbit Finance group of companies.
            Retention of Information`,
            `We retain the personal information of job applicants for a reasonable period of time to evaluate your candidacy for employment and comply with legal obligations. If your application is unsuccessful, we may retain your information for future job opportunities unless you request us to delete your information.`,
            `Security`,
            `We take appropriate technical and organizational measures to protect the personal information of job applicants against unauthorized access, disclosure, alteration, or destruction.`,
            `Data Subject Rights`,
            `Job applicants have the right to access, correct, and delete their personal information. If you wish to exercise these rights, please contact us using the information provided in the Contact Us section of this policy.`
        ]
    },
    {
        title:"Changes to this privacy poilcy",
        listItems:[
            `At Orbit Finance, we may update this privacy policy from time to time to reflect changes in our business practices, legal and regulatory requirements, or industry standards. We encourage individuals to review this privacy policy periodically to stay informed about our practices with respect to personal information. We will provide notice of any material changes to this privacy policy by posting a notice on our website or by other means as required by applicable laws and regulations. The effective date of the most recent version of this privacy policy will be indicated at the top of the page. If we make any material changes to this privacy policy, we will provide individuals with an opportunity to review and accept the updated privacy policy before the changes take effect, unless the changes are required by law or are necessary to protect the safety and security of our services or users. If individuals do not accept the updated privacy policy, their access to and use of our services may be restricted. In addition, we may provide additional notice of changes to this privacy policy as required by applicable laws and regulations, such as by email or by posting a notice on our website. `
        ]
    },
    {
        title:"Updates to the privacy poilcy",
        listItems:[
            `At Orbit Finance, we may update or modify this privacy policy from time to time to reflect changes in our information practices or legal obligations. We encourage you to review this policy periodically to stay informed about our data practices. When we make any material changes to this privacy policy, we will post a notice on our website and provide you with the opportunity to review and accept the updated policy before continuing to use our services. If you do not agree to the updated policy, you may choose to discontinue using our services. We may also notify you of changes to this privacy policy through email or other means of communication, as permitted by applicable law. By continuing to use our website or services after we have posted an updated privacy policy, you agree to the terms of the updated policy. If you have any questions or concerns about the updates, please contact us using the information provided in the Contact Us section of this policy.`
        ]
    },
    {
        title:"Disclaimer",
        listItems:[
            `The information contained in this privacy policy is provided for general informational purposes only and should not be relied upon as legal advice. While we make every effort to ensure the accuracy and completeness of the information contained herein, we cannot guarantee that it is error-free, up-to-date, or suitable for any particular purpose. Orbit Finance does not assume any responsibility or liability for any errors or omissions in the content of this privacy policy or for any actions taken based on the information contained herein. We do not endorse or recommend any particular product or service mentioned in this policy or on our website. This privacy policy applies solely to Orbit Finance and does not apply to any third-party websites or services that may be linked to or from our website. We are not responsible for the privacy practices or content of these third-party sites and encourage you to review their privacy policies before providing any personal information. By using our website or services, you acknowledge and agree that Orbit Finance is not responsible for any damages or losses that may arise from the use of this privacy policy or any other information provided on our website. You also acknowledge and agree that this privacy policy is subject to change at any time, and that it is your responsibility to review the policy periodically for any updates or changes.`,
            `If you have any questions or concerns about this privacy policy, please contact us using the information provided in the Contact Us section of this policy.`
        ]
    },
    {
        title:"Contact us",
        listItems:[
            `If you have any questions or concerns about this privacy policy or our practices regarding personal information, please contact us at privacy@orbitfinance.com. At Orbit Finance, we are committed to protecting the privacy of individuals and ensuring that their personal information is handled in accordance with this privacy policy. If individuals have any questions, comments, or concerns about this privacy policy or our privacy practices, they can contact us by using the contact details provided below. We have a dedicated team responsible for addressing privacy-related inquiries and complaints. Individuals can contact us by email or phone to make a privacy-related inquiry or complaint. We will respond to all privacy-related inquiries and complaints in a timely and efficient manner. If individuals wish to make a complaint about our handling of their personal information, they can do so by contacting us using the contact details provided below. We will investigate all complaints and provide individuals with a response in a timely manner. If individuals are not satisfied with our response to their complaint, they may have recourse to further remedies under applicable laws and regulations. In addition to our privacy-related contact details, we also provide general contact details for our company, including our address and phone number. Individuals may use these contact details to contact us for any other reason, such as to inquire about our services or to provide feedback.`,
            `By using our website and services, you agree to the terms of this Privacy Policy. If you do not agree to the terms of this Privacy Policy, please do not use our website or services.`
        ]
    }
]